from . import product_public_category
from . import website_menu
from . import website
from . import slider
from . import slider_filter
from . import website_expertise
from . import res_company
from . import product_template
from . import product_label
from . import slider_styles
from . import ir_filters
from . import ir_module_module
from . import ir_ui_view
from . import product_pricelist_item
from . import product_brand_ept
from . import product_rule
from . import product_attribute
